/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as R404RouteImport } from './app/404'
import { Route as BlogIndexRouteImport } from './app/blog/index'
import { Route as BlogDiscordAccountHackedRecoveryRouteImport } from './app/blog/discord-account-hacked-recovery'
import { Route as BlogHowHoneypotSystemsWorkRouteImport } from './app/blog/how-honeypot-systems-work'
import { Route as BlogWhatIsAHoneypotRouteImport } from './app/blog/what-is-a-honeypot'
import { Route as BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRouteImport } from './app/blog/why-im-not-worried-about-spam-bots-getting-smarter'
import { Route as DocsIndexRouteImport } from './app/docs/index'
import { Route as DocsCommandsRouteImport } from './app/docs/commands'
import { Route as DocsConfigurationRouteImport } from './app/docs/configuration'
import { Route as DocsCreditsRouteImport } from './app/docs/credits'
import { Route as DocsFaqRouteImport } from './app/docs/faq'
import { Route as DocsHowItWorksRouteImport } from './app/docs/how-it-works'
import { Route as DocsSelfHostingRouteImport } from './app/docs/self-hosting'
import { Route as DocsSetupGuideRouteImport } from './app/docs/setup-guide'
import { Route as DocsTipsRouteImport } from './app/docs/tips'
import { Route as DocsLegalPrivacyRouteImport } from './app/docs/legal/privacy'
import { Route as DocsLegalTermsRouteImport } from './app/docs/legal/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDiscordAccountHackedRecoveryRoute =
  BlogDiscordAccountHackedRecoveryRouteImport.update({
    id: '/blog/discord-account-hacked-recovery',
    path: '/blog/discord-account-hacked-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowHoneypotSystemsWorkRoute =
  BlogHowHoneypotSystemsWorkRouteImport.update({
    id: '/blog/how-honeypot-systems-work',
    path: '/blog/how-honeypot-systems-work',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhatIsAHoneypotRoute = BlogWhatIsAHoneypotRouteImport.update({
  id: '/blog/what-is-a-honeypot',
  path: '/blog/what-is-a-honeypot',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute =
  BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRouteImport.update({
    id: '/blog/why-im-not-worried-about-spam-bots-getting-smarter',
    path: '/blog/why-im-not-worried-about-spam-bots-getting-smarter',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/docs/commands',
  path: '/docs/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/docs/configuration',
  path: '/docs/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCreditsRoute = DocsCreditsRouteImport.update({
  id: '/docs/credits',
  path: '/docs/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/docs/faq',
  path: '/docs/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHowItWorksRoute = DocsHowItWorksRouteImport.update({
  id: '/docs/how-it-works',
  path: '/docs/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSelfHostingRoute = DocsSelfHostingRouteImport.update({
  id: '/docs/self-hosting',
  path: '/docs/self-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSetupGuideRoute = DocsSetupGuideRouteImport.update({
  id: '/docs/setup-guide',
  path: '/docs/setup-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTipsRoute = DocsTipsRouteImport.update({
  id: '/docs/tips',
  path: '/docs/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLegalPrivacyRoute = DocsLegalPrivacyRouteImport.update({
  id: '/docs/legal/privacy',
  path: '/docs/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLegalTermsRoute = DocsLegalTermsRouteImport.update({
  id: '/docs/legal/terms',
  path: '/docs/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/blog/discord-account-hacked-recovery': typeof BlogDiscordAccountHackedRecoveryRoute
  '/blog/how-honeypot-systems-work': typeof BlogHowHoneypotSystemsWorkRoute
  '/blog/what-is-a-honeypot': typeof BlogWhatIsAHoneypotRoute
  '/blog/why-im-not-worried-about-spam-bots-getting-smarter': typeof BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/credits': typeof DocsCreditsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/setup-guide': typeof DocsSetupGuideRoute
  '/docs/tips': typeof DocsTipsRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/legal/privacy': typeof DocsLegalPrivacyRoute
  '/docs/legal/terms': typeof DocsLegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/blog/discord-account-hacked-recovery': typeof BlogDiscordAccountHackedRecoveryRoute
  '/blog/how-honeypot-systems-work': typeof BlogHowHoneypotSystemsWorkRoute
  '/blog/what-is-a-honeypot': typeof BlogWhatIsAHoneypotRoute
  '/blog/why-im-not-worried-about-spam-bots-getting-smarter': typeof BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/credits': typeof DocsCreditsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/setup-guide': typeof DocsSetupGuideRoute
  '/docs/tips': typeof DocsTipsRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/legal/privacy': typeof DocsLegalPrivacyRoute
  '/docs/legal/terms': typeof DocsLegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/blog/discord-account-hacked-recovery': typeof BlogDiscordAccountHackedRecoveryRoute
  '/blog/how-honeypot-systems-work': typeof BlogHowHoneypotSystemsWorkRoute
  '/blog/what-is-a-honeypot': typeof BlogWhatIsAHoneypotRoute
  '/blog/why-im-not-worried-about-spam-bots-getting-smarter': typeof BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/credits': typeof DocsCreditsRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/setup-guide': typeof DocsSetupGuideRoute
  '/docs/tips': typeof DocsTipsRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/legal/privacy': typeof DocsLegalPrivacyRoute
  '/docs/legal/terms': typeof DocsLegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/blog/discord-account-hacked-recovery'
    | '/blog/how-honeypot-systems-work'
    | '/blog/what-is-a-honeypot'
    | '/blog/why-im-not-worried-about-spam-bots-getting-smarter'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/credits'
    | '/docs/faq'
    | '/docs/how-it-works'
    | '/docs/self-hosting'
    | '/docs/setup-guide'
    | '/docs/tips'
    | '/blog/'
    | '/docs/'
    | '/docs/legal/privacy'
    | '/docs/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/blog/discord-account-hacked-recovery'
    | '/blog/how-honeypot-systems-work'
    | '/blog/what-is-a-honeypot'
    | '/blog/why-im-not-worried-about-spam-bots-getting-smarter'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/credits'
    | '/docs/faq'
    | '/docs/how-it-works'
    | '/docs/self-hosting'
    | '/docs/setup-guide'
    | '/docs/tips'
    | '/blog'
    | '/docs'
    | '/docs/legal/privacy'
    | '/docs/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/blog/discord-account-hacked-recovery'
    | '/blog/how-honeypot-systems-work'
    | '/blog/what-is-a-honeypot'
    | '/blog/why-im-not-worried-about-spam-bots-getting-smarter'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/credits'
    | '/docs/faq'
    | '/docs/how-it-works'
    | '/docs/self-hosting'
    | '/docs/setup-guide'
    | '/docs/tips'
    | '/blog/'
    | '/docs/'
    | '/docs/legal/privacy'
    | '/docs/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  BlogDiscordAccountHackedRecoveryRoute: typeof BlogDiscordAccountHackedRecoveryRoute
  BlogHowHoneypotSystemsWorkRoute: typeof BlogHowHoneypotSystemsWorkRoute
  BlogWhatIsAHoneypotRoute: typeof BlogWhatIsAHoneypotRoute
  BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute: typeof BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsCreditsRoute: typeof DocsCreditsRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsHowItWorksRoute: typeof DocsHowItWorksRoute
  DocsSelfHostingRoute: typeof DocsSelfHostingRoute
  DocsSetupGuideRoute: typeof DocsSetupGuideRoute
  DocsTipsRoute: typeof DocsTipsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsLegalPrivacyRoute: typeof DocsLegalPrivacyRoute
  DocsLegalTermsRoute: typeof DocsLegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/discord-account-hacked-recovery': {
      id: '/blog/discord-account-hacked-recovery'
      path: '/blog/discord-account-hacked-recovery'
      fullPath: '/blog/discord-account-hacked-recovery'
      preLoaderRoute: typeof BlogDiscordAccountHackedRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-honeypot-systems-work': {
      id: '/blog/how-honeypot-systems-work'
      path: '/blog/how-honeypot-systems-work'
      fullPath: '/blog/how-honeypot-systems-work'
      preLoaderRoute: typeof BlogHowHoneypotSystemsWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-a-honeypot': {
      id: '/blog/what-is-a-honeypot'
      path: '/blog/what-is-a-honeypot'
      fullPath: '/blog/what-is-a-honeypot'
      preLoaderRoute: typeof BlogWhatIsAHoneypotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-im-not-worried-about-spam-bots-getting-smarter': {
      id: '/blog/why-im-not-worried-about-spam-bots-getting-smarter'
      path: '/blog/why-im-not-worried-about-spam-bots-getting-smarter'
      fullPath: '/blog/why-im-not-worried-about-spam-bots-getting-smarter'
      preLoaderRoute: typeof BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/docs/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/docs/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/credits': {
      id: '/docs/credits'
      path: '/docs/credits'
      fullPath: '/docs/credits'
      preLoaderRoute: typeof DocsCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/docs/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/how-it-works': {
      id: '/docs/how-it-works'
      path: '/docs/how-it-works'
      fullPath: '/docs/how-it-works'
      preLoaderRoute: typeof DocsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/self-hosting': {
      id: '/docs/self-hosting'
      path: '/docs/self-hosting'
      fullPath: '/docs/self-hosting'
      preLoaderRoute: typeof DocsSelfHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/setup-guide': {
      id: '/docs/setup-guide'
      path: '/docs/setup-guide'
      fullPath: '/docs/setup-guide'
      preLoaderRoute: typeof DocsSetupGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tips': {
      id: '/docs/tips'
      path: '/docs/tips'
      fullPath: '/docs/tips'
      preLoaderRoute: typeof DocsTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/legal/privacy': {
      id: '/docs/legal/privacy'
      path: '/docs/legal/privacy'
      fullPath: '/docs/legal/privacy'
      preLoaderRoute: typeof DocsLegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/legal/terms': {
      id: '/docs/legal/terms'
      path: '/docs/legal/terms'
      fullPath: '/docs/legal/terms'
      preLoaderRoute: typeof DocsLegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  BlogDiscordAccountHackedRecoveryRoute: BlogDiscordAccountHackedRecoveryRoute,
  BlogHowHoneypotSystemsWorkRoute: BlogHowHoneypotSystemsWorkRoute,
  BlogWhatIsAHoneypotRoute: BlogWhatIsAHoneypotRoute,
  BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute:
    BlogWhyImNotWorriedAboutSpamBotsGettingSmarterRoute,
  DocsCommandsRoute: DocsCommandsRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsCreditsRoute: DocsCreditsRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsHowItWorksRoute: DocsHowItWorksRoute,
  DocsSelfHostingRoute: DocsSelfHostingRoute,
  DocsSetupGuideRoute: DocsSetupGuideRoute,
  DocsTipsRoute: DocsTipsRoute,
  BlogIndexRoute: BlogIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsLegalPrivacyRoute: DocsLegalPrivacyRoute,
  DocsLegalTermsRoute: DocsLegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
